export * from './Header'
export * from './GenreContainer'
export * from './MoviesContainer'
export * from './Poster'
export * from './UserIcon'
export * from './StarsRating'
export * from './Pagination'